name: firebase_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.8
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.0.2
  http: ^0.13.5
  provider: ^6.0.5
  rounded_loading_button: ^2.1.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
